name: "Build"

on: [push, pull_request]

jobs:
  Matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Matrix
        id: matrix
        uses: Invicton-Labs/terraform-module-testing/matrix@feat/additional-os
        with:
          minimum_tf_version: '1.7.0'
          additional_runners: 'macos-13, windows-2019'
          additional_images: 'amazonlinux:2'

      - name: Output Matrix
        run: |
          echo "Strategy: ${{ steps.matrix.outputs.strategy }}"

    outputs:
      strategy: ${{ steps.matrix.outputs.strategy }}
          
  Test:
    needs: [Matrix]
    strategy: ${{ fromJSON(needs.Matrix.outputs.strategy)}}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    steps:
      - name: Initialize - Pass
        id: init-pass
        uses: Invicton-Labs/terraform-module-testing/initialize@feat/additional-os
        with:
          tf_path: tests/pass
      - name: Run Tests - Pass
        id: tests-pass
        uses: Invicton-Labs/terraform-module-testing/apply-destroy@feat/additional-os
        with:
          tf_path: tests/pass
          
      - name: Initialize - Fail
        id: init-fail
        uses: Invicton-Labs/terraform-module-testing/initialize@feat/additional-os
        with:
          tf_path: tests/fail
      - name: Run Tests - Fail
        id: tests-fail
        uses: Invicton-Labs/terraform-module-testing/apply-failure@feat/additional-os
        with:
          tf_path: tests/fail
          
  # This job just waits for all other jobs to pass. We have it here
  # so our branch protection rule can reference a single job, instead
  # of needing to list every matrix value of every job above.
  Passed:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - name: Mark tests as passed
      run: echo "🎉"
